---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moodbot

resources:
  - configmap.yaml
  - deployment-web.yaml
  - deployment-poller.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
